services:
  omp-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  omp-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - omp-server